version: '3'

services:
  kartoffel:
    image: kartoffel
    build: .
    env_file: docker-compose.env
    ports:
      - 3000:3000
    depends_on:
      - mongo-primary
      - mongo-secondary
      # - mongo-replicator
      - elasticsearch
      - es_init

  mongo-primary:
    image: bitnami/mongodb:latest
    environment: 
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=mongo-primary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_ROOT_PASSWORD=nitro123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - 27017:27017

  mongo-secondary:
    image: bitnami/mongodb:latest
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_ADVERTISED_HOSTNAME=mongo-secondary
      - MONGODB_PRIMARY_HOST=mongo-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_PRIMARY_ROOT_PASSWORD=nitro123
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - 27018:27017
    depends_on: 
      - mongo-primary
  
  # mongo-replicator:
  #   image: eladex/mongo-replicator
  #   depends_on:
  #     - mongo-primary
  #     - mongo-secondary

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200

  monstache:
    image: eladex/monstache-wrapper
    depends_on: 
      - mongo-primary
      - mongo-secondary
      - elasticsearch
      - es_init
  es_init:
    image: eladex/kartoffel-es-init
    depends_on: 
      - elasticsearch
    environment: 
      - ES_HOSTS=http://elasticsearch:9200
      - INDEX_NAME=kartoffel.people

  